services:
  web:
    image: ghcr.io/darthmaim/gw2boost.com/web:${IMAGE_VERSION:-latest}
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://gw2boost:gw2boost@database:5432/gw2boost?schema=public
      - BASE_URL=http://localhost:3000
    ports:
      - 3000:3000

  database:
    image: timescale/timescaledb:2.17.2-pg17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gw2boost
      - POSTGRES_PASSWORD=gw2boost
      - POSTGRES_DB=gw2boost
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .docker/database-pg17:/var/lib/postgresql/data
    ports:
      - 54328:5432

  database-migration:
    image: ghcr.io/darthmaim/gw2boost.com/database-migration:${IMAGE_VERSION:-latest}
    build:
      context: .
      dockerfile: apps/database-migration/Dockerfile
    restart: on-failure:5
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://gw2boost:gw2boost@database:5432/gw2boost?schema=public
