apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gw2boost

commonLabels:
  app.kubernetes.io/part-of: gw2boost

resources:
- ../base
- database
- web

images:
- name: ghcr.io/darthmaim/gw2boost.com/web
  newTag: latest

- name: ghcr.io/darthmaim/gw2boost.com/database-migration
  newTag: latest

- name: ghcr.io/darthmaim/gw2boost.com/demo
  newTag: latest
