name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  IMAGE_VERSION: ci-run-${{ github.run_id }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-node.yml

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  success:
    name: Success
    needs: [build, lint]
    runs-on: ubuntu-24.04
    if: always()
    steps:
    - name: Check job status
      run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Success
      run: exit 0
