name: Build Docker images
on:
  workflow_call:

env:
  IMAGE_VERSION: ci-run-${{ github.run_id }}

jobs:
  build-docker:
    name: "Build: ${{ matrix.target }}"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [ web, database-migration ]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      uses: docker/bake-action@v5.11.0
      with:
        files: ./compose.yml
        targets: ${{ matrix.target }}
        set: |
          ${{ matrix.target }}.output=type=image,push=true
          *.platform=linux/amd64,linux/arm64
          *.cache-from=type=gha,scope=build-${{ matrix.target }}
          *.cache-to=type=gha,scope=build-${{ matrix.target }},mode=max
